Model:
    CharSet: [' ', '9', P, H, V, W, T, B, C, A, M, U, Z, '7', '4', R, E, '1', O, '2',
        G, '5', X, I, '3', F, Y, K, L, S, Q, J, D, N]
    ImageChannel: 1
    ImageHeight: 64
    ImageWidth: -1
    Word: false
System:
    Allow_Ext: [jpg, jpeg, png, bmp]
    GPU: false
    GPU_ID: 0
    Path: ../captcha_data/labeled/apple
    Project: apple_captcha
    Val: 0.15
Train:
    BATCH_SIZE: 32
    CNN: {NAME: ddddocr}
    DROPOUT: 0.3
    LR: 0.01
    OPTIMIZER: SGD
    SAVE_CHECKPOINTS_STEP: 200
    TARGET: {Accuracy: 0.7, Cost: 0.05, Epoch: 20}
    TEST_BATCH_SIZE: 32
    TEST_STEP: 50
