Model:
    CharSet: [' ', X, V, N, K, G, E, U, Z, B, A, J, D, '3', Y, '9', '7', Q, P, '2',
        L, W, R, I, M, S, F, '4', C, H, T]
    ImageChannel: 1
    ImageHeight: 64
    ImageWidth: -1
    Word: false
System:
    Allow_Ext: [jpg, jpeg, png, bmp]
    GPU: false
    GPU_ID: 0
    Path: ../captcha_data/labeled/apple
    Project: apple_captcha
    Val: 0.03
Train:
    BATCH_SIZE: 32
    CNN: {NAME: ddddocr}
    DROPOUT: 0.3
    LR: 0.01
    OPTIMIZER: SGD
    SAVE_CHECKPOINTS_STEP: 2000
    TARGET: {Accuracy: 1.0, Cost: 0.05, Epoch: 20}
    TEST_BATCH_SIZE: 32
    TEST_STEP: 1000
