Model:
    CharSet: [' ', I, U, '7', '4', M, C, '3', '5', T, '9', F, Y, A, '1', S, W, E,
        G, Z, N, O, J, V, X, P, L, K, H, '2', B, R, D, Q]
    ImageChannel: 1
    ImageHeight: 64
    ImageWidth: -1
    Word: false
System:
    Allow_Ext: [jpg, jpeg, png, bmp]
    GPU: false
    GPU_ID: 0
    Path: /Users/zhouliang/Desktop/work/github/captcha_alpha/captcha_data/labeled/apple
    Project: apple_captcha
    Val: 0.15
Train:
    BATCH_SIZE: 32
    CNN: {NAME: ddddocr_beta}
    DROPOUT: 0.3
    LR: 0.001
    NUM_WORKERS: 0
    OPTIMIZER: SGD
    SAVE_CHECKPOINTS_STEP: 200
    TARGET: {Accuracy: 0.85, Cost: 0.05, Epoch: 20}
    TEST_BATCH_SIZE: 32
    TEST_STEP: 50
